---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-sent-analyst
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/stock-sent-analyst.git
    targetRevision: main
    path: charts/stock-sent-analyst
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
