---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: default

labels:
  - includeSelectors: true
    pairs:
      app: stock-sent-analyst

images:
  - name: stock-sent-analyst
    newName: stock-sent-analyst
    newTag: latest
